### ISSUE TITLE
Source code for RF100 V2 Marlin 2.0.4.4.hex

### ISSUE THREAD

**Issue by piotrkochan** [dok-net/RF100#1]
HIi great work!
Could You share RF100 V2 Marlin 2.0.4.4.hex source code? Or at least Configuration.h?
Thanks

**Comment by piotrkochan** [comment]
I've found it https://github.com/dok-net/Marlin/tree/renkforce_rf100_v2

**Comment by piotrkochan** [comment]
I'm reopening the issue because Marlin 2.0 Configuration.h and adv is unpopulated.
https://github.com/dok-net/Marlin/blob/2.0.x-renkforce_rf100/Marlin/Configuration.h

**Comment by dok-net** [comment]
This time you're taking too long to find your mistake by yourself :-)
Hint: https://github.com/dok-net/Marlin/blob/rf100-v3.0.6/config/README.md
