### ISSUE TITLE
Please, i need help quickly ||  Bitte, ich brauche schnell Hilfe

### ISSUE THREAD

**Issue by hapi-dev** [dok-net/RF100#3]
Hello, i have rf100 printer but i updated firmawre to v1.1 and filament change doesnt work. Where can i find rf100 v1.0 firmware!
If you have please send me to email: august2mcon@gmail.com

GERMANY:
Hallo, ich habe rf100 Drucker, aber ich habe firmawre auf v1.1 aktualisiert und Filamentwechsel funktioniert nicht. Wo finde ich die Firmware von rf100 v1.0?
Wenn ja, senden Sie mir bitte eine E-Mail an: august2mcon@gmail.com

**Comment by dok-net** [comment]
@hapi-dev I would like to invite you to install the latest version of the firmware for your RF100 V1, V2, or XL from here. Besides, I don't recall noticing any difference in the filament unload feature when updating from "Renkforce's" release 1.0 to 1.1. I can't help you with the 1.0 firmware, but never mind, just upgrade to what's offered here. It's a bit different, as Marlin has evolved quite a bit, and the Renkforce firmware was heavily modded, but once you do, you're part of the open-source ecosystem :-)
